version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  python-flask:
    build: ./python-flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
